### ISSUE TITLE
Tooling roadmap

### ISSUE THREAD

**Issue by LPeter1997** [Draco-lang/Compiler#173]
* [ ] Give the language server a CLI
 * [ ] Finish the SDK and Tooling packages, the SDK shipping the targets, the Tooling package shipping the compiler CLI and the language server CLI
 * [ ] Make the .NET tool be able to create a Draco projectfile
 * [ ] Make the SDK and Tooling packages automatically publishable from CI
 * [ ] Make the VS Code extension discover .NET on the machine ([might be helpful tool](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/vscode-dotnet-runtime))
 * [ ] Make the VS Code extension add build settings/config when recognizing a Draco project folder
 * [ ] Make the VS Code extension automatically publishable from CI
