### ISSUE TITLE
Language features roadmap

### ISSUE THREAD

**Issue by jakubbinter** [Draco-lang/Compiler#191]
- [ ] [local functions inside other functions](https://github.com/Draco-lang/Language-suggestions/blob/main/Specification/ControlFlow.md#semantics)
- [ ] [rest of builtin types](https://github.com/Draco-lang/Language-suggestions/blob/main/Specification/ExpressionsAndBuiltins.md#built-in-primitive-types)
- [ ] [hexadecimal and binary integers](https://github.com/Draco-lang/Language-suggestions/blob/main/Specification/ExpressionsAndBuiltins.md#integer-literals)
- [ ] [scientific notation for floats](https://github.com/Draco-lang/Language-suggestions/blob/main/Specification/ExpressionsAndBuiltins.md#floating-point-literals)
